spring.application.name=BISTradeBackend
server.port=8090
server.address=127.0.0.1
server.forward-headers-strategy=framework

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:mysql://localhost:3306/bistrade
spring.datasource.username=root
spring.datasource.password=root